version: '3.7'

services:
  ssh-resumable-upload:
    container_name: ssh-resumable-upload
    build:
      context: ./
    ports:
      - "2233:2233"
    volumes:
      - ./uploads:/home/dropbear/uploads
